# Generated by Django 4.1.7 on 2023-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_name', models.CharField(max_length=150)),
                ('cake_weight', models.PositiveIntegerField()),
                ('cake_price', models.PositiveIntegerField()),
                ('cake_image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
